# This is the workflow to validate a PR
#
name: Lint Pull Request

on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  lint-pr:
    name: '🕵️‍♂️ Lint Commit Message'
    runs-on: ubuntu-latest

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      # check for the most recent release: https://github.com/Namchee/conventional-pr/releases
      - name: '✅ Lint PR'
        uses: Namchee/conventional-pr@v0.15.5
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          label: '⁉️ invalid'
          branch_pattern: ''
          message: "The PR doesn't match the requirements"
