# This is workflow runs on push
#
name: Release

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cancel-runs:
    name: '▶️ actions'
    uses: ./.github/workflows/cancel-workflow.yml

  lint-code:
    name: '▶️ actions'
    needs: [cancel-runs]
    uses: ./.github/workflows/lint-code.yml

  codeql:
    name: '▶️ actions'
    needs: [lint-code]
    uses: ./.github/workflows/codeql.yml

  release:
    name: '▶️ actions'
    needs: [lint-code, codeql]
    uses: ./.github/workflows/release.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }} # Token with repo write permission & admin rights to push to protected branches
